### ISSUE TITLE
Error in CuDNN: CUDNN_STATUS_BAD_PARAM (cudnnSetConvolutionNdDescriptor)

### ISSUE THREAD

**Issue by barrykui** [facebook/fb.resnet.torch#139]
I encounter these error messages, when run cifar10 with 2 GPUs. Command line is `CUDA_VISIBLE_DEVICES=0,1 th main.lua -depth 50 -batchSize 1024 -nGPU 2 -nThreads 8 -shareGradInput true -dataset cifar10` .

```
/home/scs4850/torch/install/share/lua/5.1/cudnn/init.lua:162: Error in CuDNN: CUDNN_STATUS_BAD_PARAM (cudnnSetConvolutionNdDescriptor)
stack traceback:
        [C]: in function 'error'
        /home/scs4850/torch/install/share/lua/5.1/cudnn/init.lua:162: in function 'errcheck'
        /home/scs4850/torch/install/share/lua/5.1/cudnn/init.lua:217: in function 'setConvolutionDescriptor'
        ...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:130: in function 'createIODescriptors'
        ...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:187: in function <...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:185>
        [C]: in function 'xpcall'
        /home/scs4850/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        /home/scs4850/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/scs4850/torch/install/share/lua/5.1/nn/Sequential.lua:41>
        [C]: in function 'xpcall'
        /home/scs4850/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        ...
        /home/scs4850/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/scs4850/torch/install/share/lua/5.1/nn/Sequential.lua:41>
        [C]: in function 'xpcall'
        /home/scs4850/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        /home/scs4850/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/scs4850/torch/install/share/lua/5.1/nn/Sequential.lua:41>
        [C]: in function 'xpcall'
        .../scs4850/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
        /home/scs4850/torch/install/share/lua/5.1/threads/queue.lua:65: in function </home/scs4850/torch/install/share/lua/5.1/threads/queue.lua:41>
        [C]: in function 'pcall'
        /home/scs4850/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
        [string "  local Queue = require 'threads.queue'..."]:13: in main chunk

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
        [C]: in function 'error'
        /home/scs4850/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
        /home/scs4850/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/scs4850/torch/install/share/lua/5.1/nn/Sequential.lua:41>
        [C]: in function 'xpcall'
        .../scs4850/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
        /home/scs4850/torch/install/share/lua/5.1/threads/queue.lua:65: in function </home/scs4850/torch/install/share/lua/5.1/threads/queue.lua:41>
        [C]: in function 'pcall'
        /home/scs4850/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
        [string "  local Queue = require 'threads.queue'..."]:13: in main chunk
stack traceback:
        [C]: in function 'error'
        .../scs4850/torch/install/share/lua/5.1/threads/threads.lua:183: in function 'dojob'
        .../scs4850/torch/install/share/lua/5.1/threads/threads.lua:264: in function 'synchronize'
        ...0/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:717: in function 'exec'
        ...0/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:195: in function 'forward'
        ./train.lua:116: in function 'test'
        main.lua:52: in main chunk
        [C]: in function 'dofile'
        ...4850/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670
```

Anyone here could help me?

**Comment by colesbury** [comment]
Are you running out of memory? Does it work with a smaller batch size? You may also want to run it with `CUDA_LAUNCH_BLOCKING=1` -- it will run more slowly, but should make the print message where it occurred (otherwise, errors may be asynchronously reported later on in the code)

**Comment by barrykui** [comment]
Thank you for your reply! @colesbury 
It only used 1/5 memory. The error encountered after about 50 epoch.
I'll test CUDA_LAUNCH_BLOCKING=1 with 2 GPU.

**Comment by barrykui** [comment]
@colesbury I test many times, found that sometimes it run smoothly without any error with 2 or 4 GPUs, but never succeed on 8 GPUs. 
The errors are about  `Error in CuDNN: CUDNN_STATUS_BAD_PARAM`, but  sometimes  with different type between `cudnnSetConvolutionNdDescriptor` (details have been showed above) and `cudnnSetConvolutionNdDescriptor` (details showed below). 


```
nGPU:8
=> Creating model from file: models/resnet.lua
 | ResNet-50 CIFAR-10
=> Training epoch # 1
datarun=self.batchSize:4096
 | Epoch: [1][1/13]    Time 21.782  Data 0.569  Err 2.8343  top1  89.307  top5  50.977
 | Epoch: [1][2/13]    Time 0.850  Data 0.000  Err 5.6519  top1  87.451  top5  49.414
 | Epoch: [1][3/13]    Time 0.727  Data 0.000  Err 7.3821  top1  87.915  top5  52.222
 | Epoch: [1][4/13]    Time 0.733  Data 0.000  Err 6.0005  top1  90.015  top5  49.438
 | Epoch: [1][5/13]    Time 0.728  Data 0.000  Err 4.6338  top1  90.088  top5  47.778
 | Epoch: [1][6/13]    Time 0.729  Data 0.000  Err 4.7883  top1  86.963  top5  48.071
 | Epoch: [1][7/13]    Time 0.732  Data 0.000  Err 5.0234  top1  91.113  top5  51.074
 | Epoch: [1][8/13]    Time 0.732  Data 0.000  Err 3.5210  top1  90.894  top5  50.781
 | Epoch: [1][9/13]    Time 7.450  Data 0.000  Err 2.9324  top1  87.854  top5  44.929
 | Epoch: [1][10/13]    Time 1.196  Data 0.000  Err 2.5048  top1  87.573  top5  43.018
 | Epoch: [1][11/13]    Time 0.730  Data 0.000  Err 2.4233  top1  87.842  top5  45.435
 | Epoch: [1][12/13]    Time 0.732  Data 0.000  Err 2.3594  top1  87.158  top5  45.508
 | Epoch: [1][13/13]    Time 0.728  Data 0.000  Err 2.3344  top1  89.258  top5  47.437
datarun=self.batchSize:4096
/home/scs4850/torch/install/bin/luajit: .../scs4850/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 3 callback] /home/scs4850/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 5 module of nn.Sequential:
In 5 module of nn.Sequential:
In 1 module of nn.Sequential:
In 1 module of nn.ConcatTable:
In 1 module of nn.Sequential:
/home/scs4850/torch/install/share/lua/5.1/cudnn/init.lua:162: Error in CuDNN: CUDNN_STATUS_BAD_PARAM (cudnnGetConvolutionNdForwardOutputDim)
stack traceback:
        [C]: in function 'error'
        /home/scs4850/torch/install/share/lua/5.1/cudnn/init.lua:162: in function 'errcheck'
        ...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:139: in function 'createIODescriptors'
        ...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:187: in function <...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:185>
        [C]: in function 'xpcall'
        /home/scs4850/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        /home/scs4850/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/scs4850/torch/install/share/lua/5.1/nn/Sequential.lua:41>
        [C]: in function 'xpcall'
        /home/scs4850/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        ...e/scs4850/torch/install/share/lua/5.1/nn/ConcatTable.lua:11: in function <...e/scs4850/torch/install/share/lua/5.1/nn/ConcatTable.lua:9>
        ...
        /home/scs4850/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/scs4850/torch/install/share/lua/5.1/nn/Sequential.lua:41>
        [C]: in function 'xpcall'
        /home/scs4850/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        /home/scs4850/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/scs4850/torch/install/share/lua/5.1/nn/Sequential.lua:41>
        [C]: in function 'xpcall'
        .../scs4850/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
        /home/scs4850/torch/install/share/lua/5.1/threads/queue.lua:65: in function </home/scs4850/torch/install/share/lua/5.1/threads/queue.lua:41>
        [C]: in function 'pcall'
        /home/scs4850/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
        [string "  local Queue = require 'threads.queue'..."]:13: in main chunk

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
        [C]: in function 'error'
        /home/scs4850/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
        /home/scs4850/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/scs4850/torch/install/share/lua/5.1/nn/Sequential.lua:41>
        [C]: in function 'xpcall'
        .../scs4850/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
        /home/scs4850/torch/install/share/lua/5.1/threads/queue.lua:65: in function </home/scs4850/torch/install/share/lua/5.1/threads/queue.lua:41>
        [C]: in function 'pcall'
        /home/scs4850/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
        [string "  local Queue = require 'threads.queue'..."]:13: in main chunk
stack traceback:
        [C]: in function 'error'
        .../scs4850/torch/install/share/lua/5.1/threads/threads.lua:183: in function 'dojob'
        .../scs4850/torch/install/share/lua/5.1/threads/threads.lua:264: in function 'synchronize'
        ...0/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:717: in function 'exec'
        ...0/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:195: in function 'forward'
        ./train.lua:132: in function 'test'
        main.lua:52: in main chunk
        [C]: in function 'dofile'
        ...4850/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

```

**Comment by colesbury** [comment]
I'm not having any cuDNN problems on 8 GPUs. Are your libraries (cuDNN, cutorch, cunn) up to date? I tried your command:

`th main.lua -depth 50 -batchSize 4096 -nGPU 8 -nThreads 8 -shareGradInput true -dataset cifar10`

```
=> Creating model from file: models/resnet.lua
 | ResNet-50 CIFAR-10
=> Training epoch # 1
 | Epoch: [1][1/13]    Time 10.156  Data 0.593  Err 2.8225  top1  90.210  top5  51.099
 | Epoch: [1][2/13]    Time 0.184  Data 0.000  Err 5.6730  top1  87.109  top5  49.072
 | Epoch: [1][3/13]    Time 0.330  Data 0.000  Err 7.2386  top1  90.576  top5  47.217
 | Epoch: [1][4/13]    Time 0.319  Data 0.000  Err 6.4887  top1  91.504  top5  50.952
 | Epoch: [1][5/13]    Time 0.491  Data 0.000  Err 4.3099  top1  89.355  top5  47.485
 | Epoch: [1][6/13]    Time 0.320  Data 0.000  Err 3.7838  top1  85.352  top5  45.703
 | Epoch: [1][7/13]    Time 0.320  Data 0.000  Err 4.0815  top1  86.304  top5  47.339
 | Epoch: [1][8/13]    Time 0.320  Data 0.000  Err 2.9000  top1  87.939  top5  49.561
 | Epoch: [1][9/13]    Time 2.747  Data 0.000  Err 2.7411  top1  90.094  top5  50.354
 | Epoch: [1][10/13]    Time 0.188  Data 0.000  Err 3.0741  top1  90.088  top5  47.754
 | Epoch: [1][11/13]    Time 0.325  Data 0.000  Err 2.6198  top1  88.330  top5  48.413
 | Epoch: [1][12/13]    Time 0.322  Data 0.000  Err 2.4604  top1  88.916  top5  48.047
 | Epoch: [1][13/13]    Time 0.320  Data 0.000  Err 2.3873  top1  89.624  top5  48.682
 | Test: [1][1/3]    Time 2.694  Data 0.128  top1  89.049 ( 89.049)  top5  49.834 ( 49.834)
 | Test: [1][2/3]    Time 0.104  Data 0.000  top1  89.819 ( 89.583)  top5  49.146 ( 49.356)
 | Test: [1][3/3]    Time 0.105  Data 0.000  top1  90.601 ( 90.000)  top5  51.074 ( 50.060)
 * Finished epoch # 1     top1:  90.000  top5:  50.060

 * Best model   90      50.06
=> Training epoch # 2
 | Epoch: [2][1/13]    Time 0.638  Data 0.396  Err 2.3702  top1  89.502  top5  48.462
 | Epoch: [2][2/13]    Time 0.326  Data 0.000  Err 2.3689  top1  90.991  top5  49.829
 | Epoch: [2][3/13]    Time 0.321  Data 0.001  Err 2.3318  top1  89.380  top5  48.950
 | Epoch: [2][4/13]    Time 0.320  Data 0.000  Err 2.3343  top1  90.234  top5  48.804
 | Epoch: [2][5/13]    Time 0.320  Data 0.000  Err 2.3246  top1  90.381  top5  50.830
...
```

**Comment by kartynnik** [comment]
@barrykui Having experienced the same issues as yours (rare and random `CUDNN_STATUS_BAD_PARAM`s with `cudnnSetConvolutionNdDescriptor` and `cudnnGetConvolutionNdForwardOutputDim`, which had no identifiable arguments that are "bad" according to the CuDNN User Guide upon inspection), we seem to have avoided them by downgrading from `libcudnn.so.5.1.5` to `libcudnn.so.5.1.3`.

**Comment by gchanan** [comment]
This should be fixed if you install the latest the cudnn.torch.

**Comment by HusainKapadia** [comment]
I have the same error but while training. I implemented a U-Net type architecture and I am getting an error for a convTranspose2D. All of this is being implemented on cuda. On cpu this same cord works fine. 
`   
class sampleUNet(nn.module) :
    def __init__(self) :
        super().__init__()
                   
        self.down_conv1 = nn.Conv2d(1, 32, (5, 1))
        self.BN1 = nn.BatchNorm2d(32)
        self.down_conv2 = nn.Conv2d(32, 64, (5, 1))
        self.BN2 = nn.BatchNorm2d(64)
        self.down_conv3 = nn.Conv2d(64, 128, (5, 1))
        self.BN3 = nn.BatchNorm2d(128)
        self.up_conv1 = nn.ConvTranspose2d(128, 64, (5, 1))
        self.BN4 = nn.BatchNorm2d(64)
        self.up_conv2 = nn.ConvTranspose2d(64, 32, (5, 1))
        self.BN5 = nn.BatchNorm2d(32)
        self.up_conv3 = nn.ConvTranspose2d(32, 1, (5, 1))
        self.BN6 = nn.BatchNorm2d(1)
        
        num_params(self)
        self.criterion = torch.nn.L1Loss().to(device)
        
    def loss(self, output, target):
        print('5', output.size(), target.contiguous().size())
        return self.criterion(output, target.contiguous())
    
    def forward(self, m) :
        input_ = m.unsqueeze(1)
        
        m = self.down_conv1(input_)
        print('1', m.size())
        skip1 = m
        m = F.relu(self.BN1(m))
        
        m = self.down_conv2(m)
        print('2', m.size())
        skip2 = m
        m = F.relu(self.BN2(m))
        
        m = F.relu(self.BN3(self.down_conv3(m)))
        print('3', m.size())
        
        m = self.up_conv1(m)     <------ error here
        print('4', m.size())
        m += skip2
        m = F.relu(self.BN4(m))
        
        m = self.up_conv2(m)
        m += skip1
        m = F.relu(self.BN5(m))
        
        m = self.up_conv3(m)
        m += input_
        m = F.relu(self.BN6(m))
        
        m = m.squeeze(1)
    
        return m
`
the output and error are 

`
1 torch.Size([64, 32, 76, 10])
2 torch.Size([64, 64, 72, 10])
3 torch.Size([64, 128, 68, 10])
Traceback (most recent call last):
  File "train.py", line 156, in <module>
    train(model, optimiser, epochs=config.num_epochs, batch_size=bs, step=step, lr=1e-4)
  File "train.py", line 101, in train
    m_hat = model(m)
  File "/home/hkapadia/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hkapadia/project/network.py", line 219, in forward
    m = self.up_conv1(m)
  File "/home/hkapadia/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hkapadia/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 757, in forward
    output_padding, self.groups, self.dilation)
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM
`

Please help
